<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('brands')->insert([
            ["name" => "Acura", "fipe_id" => 1],
            ["name" => "Agrale", "fipe_id" => 2],
            ["name" => "Alfa Romeo", "fipe_id" => 3],
            ["name" => "AM Gen", "fipe_id" => 4],
            ["name" => "Asia Motors", "fipe_id" => 5],
            ["name" => "Audi", "fipe_id" => 6],
            ["name" => "BMW", "fipe_id" => 7],
            ["name" => "BRM", "fipe_id" => 8],
            ["name" => "Cadillac", "fipe_id" => 10],
            ["name" => "CBT Jipe", "fipe_id" => 11],
            ["name" => "Chrysler", "fipe_id" => 12],
            ["name" => "Citroën", "fipe_id" => 13],
            ["name" => "Cross Lander", "fipe_id" => 14],
            ["name" => "Daewoo", "fipe_id" => 15],
            ["name" => "Daihatsu", "fipe_id" => 16],
            ["name" => "Dodge", "fipe_id" => 17],
            ["name" => "Engesa", "fipe_id" => 18],
            ["name" => "Envemo", "fipe_id" => 19],
            ["name" => "Ferrari", "fipe_id" => 20],
            ["name" => "Fiat", "fipe_id" => 21],
            ["name" => "Ford", "fipe_id" => 22],
            ["name" => "GM - Chevrolet", "fipe_id" => 23],
            ["name" => "Gurgel", "fipe_id" => 24],
            ["name" => "Honda", "fipe_id" => 25],
            ["name" => "Hyundai", "fipe_id" => 26],
            ["name" => "Isuzu", "fipe_id" => 27],
            ["name" => "Jaguar", "fipe_id" => 28],
            ["name" => "Jeep", "fipe_id" => 29],
            ["name" => "JPX", "fipe_id" => 30],
            ["name" => "Kia Motors", "fipe_id" => 31],
            ["name" => "Lada", "fipe_id" => 32],
            ["name" => "Land Rover", "fipe_id" => 33],
            ["name" => "Lexus", "fipe_id" => 34],
            ["name" => "Lotus", "fipe_id" => 35],
            ["name" => "Maserati", "fipe_id" => 36],
            ["name" => "Matra", "fipe_id" => 37],
            ["name" => "Mazda", "fipe_id" => 38],
            ["name" => "Mercedes-Benz", "fipe_id" => 39],
            ["name" => "Mercury", "fipe_id" => 40],
            ["name" => "Mitsubishi", "fipe_id" => 41],
            ["name" => "Miura", "fipe_id" => 42],
            ["name" => "Nissan", "fipe_id" => 43],
            ["name" => "Peugeot", "fipe_id" => 44],
            ["name" => "Plymouth", "fipe_id" => 45],
            ["name" => "Pontiac", "fipe_id" => 46],
            ["name" => "Porsche", "fipe_id" => 47],
            ["name" => "Renault", "fipe_id" => 48],
            ["name" => "Rover", "fipe_id" => 49],
            ["name" => "Saab", "fipe_id" => 50],
            ["name" => "Saturn", "fipe_id" => 51],
            ["name" => "Seat", "fipe_id" => 52],
            ["name" => "Subaru", "fipe_id" => 54],
            ["name" => "Suzuki", "fipe_id" => 55],
            ["name" => "Toyota", "fipe_id" => 56],
            ["name" => "Troller", "fipe_id" => 57],
            ["name" => "Volvo", "fipe_id" => 58],
            ["name" => "VW - VolksWagen", "fipe_id" => 59],
            ["name" => "Walk", "fipe_id" => 120],
            ["name" => "Bugre", "fipe_id" => 123],
            ["name" => "SSANGYONG", "fipe_id" => 125],
            ["name" => "LOBINI", "fipe_id" => 127],
            ["name" => "CHANA", "fipe_id" => 136],
            ["name" => "Mahindra", "fipe_id" => 140],
            ["name" => "EFFA", "fipe_id" => 147],
            ["name" => "Fibravan", "fipe_id" => 149],
            ["name" => "HAFEI", "fipe_id" => 152],
            ["name" => "GREAT WALL", "fipe_id" => 153],
            ["name" => "JINBEI", "fipe_id" => 154],
            ["name" => "MINI", "fipe_id" => 156],
            ["name" => "smart", "fipe_id" => 157],
            ["name" => "Caoa Chery/Chery", "fipe_id" => 161],
            ["name" => "Wake", "fipe_id" => 163],
            ["name" => "TAC", "fipe_id" => 165],
            ["name" => "MG", "fipe_id" => 167],
            ["name" => "LIFAN", "fipe_id" => 168],
            ["name" => "Fyber", "fipe_id" => 170],
            ["name" => "LAMBORGHINI", "fipe_id" => 171],
            ["name" => "JAC", "fipe_id" => 177],
            ["name" => "CHANGAN", "fipe_id" => 182],
            ["name" => "SHINERAY", "fipe_id" => 183],
            ["name" => "RAM", "fipe_id" => 185],
            ["name" => "RELY", "fipe_id" => 186],
            ["name" => "ASTON MARTIN", "fipe_id" => 189],
            ["name" => "FOTON", "fipe_id" => 190],
            ["name" => "Rolls-Royce", "fipe_id" => 195],
            ["name" => "GEELY", "fipe_id" => 199],
            ["name" => "Baby", "fipe_id" => 207],
            ["name" => "IVECO", "fipe_id" => 208],
            ["name" => "Mclaren", "fipe_id" => 211],
            ["name" => "HITECH ELECTRIC", "fipe_id" => 214],
            ["name" => "CAB Motors", "fipe_id" => 236],
            ["name" => "BYD", "fipe_id" => 238],
            ["name" => "GWM", "fipe_id" => 240],
            ["name" => "D2D Motors", "fipe_id" => 241],
            ["name" => "Caoa Chery", "fipe_id" => 245],
            ["name" => "DFSK", "fipe_id" => 246],
            ["name" => "SERES", "fipe_id" =>  247]
        ]);
    }
}
